### ISSUE TITLE
Autoformat delay when using Ack.vim

### ISSUE THREAD

**Issue by mMontu** [MarcWeber/vim-addon-qf-layout#3]
There seems to be an odd interaction between this plugin and [Ack.vim](https://github.com/mileszs/ack.vim) when a default formatter (other than 'NOP') is selected.

For example, executing the following command:

    let start = reltime() | exe 'Ack! --follow "<pattern>"' | echo reltimestr(reltime(start))

, with the cwd set to a directory containing a single file where `<pattern>` matches only once, returns 2.18 (seconds) if the first element of `g:vim_addon_qf_layout.quickfix_formatters` is  `'vim_addon_qf_layout#FormatterNoFilename'`. Repeating the same command with `'NOP'` as the first element echoes 0.18.

The formatter does NOT affect the time if `vimgrep` is used:

    let start = reltime() | exe 'vim /<pattern>/j * | cw ' | echom reltimestr(reltime(start))

, which takes 1.2 seconds, no matter what is the first element `g:vim_addon_qf_layout.quickfix_formatters`. `:cs` doesn't show any problem as well.

The delay occurs while deleting the previous contents of the quickfix window (`%delete`). Adding `noautocmd` doesn't help, despite it seems the problem is related to syntax highlight (`syntax off` removes the problem).

The problem doesn't occurs if the formatting is applied *after* the quickfix is loaded, i.e., typing the mapping from `g:vim_addon_qf_layout.lhs_cycle` after the quickfix results are already visible.

**Comment by MarcWeber** [comment]
I'm not interested in spending much time on qf-layout. If you come up with a pull request I'll have a look at it.
